### ISSUE TITLE
Would be nice if the HKX files could be edited or read

### ISSUE THREAD

**Issue by SpicyCupcakes** [Greavesy1899/MafiaToolkit#34]
Sure, this tool decompiles sds files, but 99% of the files cannot be edited, especially the HKX files, and them being the only files I actually wanted to edit since Kamzik123 is a selfish piece of shit and wont tell how to edit the files, even though he knows exactly how to do it, but only wants their close friends to use it... but who in their right mind would or could be friends with an dishonored prick.

**Comment by Greavesy1899** [comment]
First of all - there is no need to be argumentative and be very aggressive towards another person. What is that going to achieve? Absolutely nothing. So put your toys back in your pram and sort your way of thinking out otherwise you're going to get absolutely nowhere.

Second of all - No. I won't be making tools to open HKX format anytime soon. Havok is a rather complicated format and many tools already exist. You just need to find them and do some research. Just like Kamzik123 did.
